# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpt_uni_modf <- function(chain) {
    .Call(`_cptmcmc_cpt_uni_modf`, chain)
}

cpt_multi_modf <- function(chain) {
    .Call(`_cptmcmc_cpt_multi_modf`, chain)
}

